name: CI Pipeline
on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y

      - name: Run tests and build examples
        run: xvfb-run script/build.sh

      - name: Upload examples
        uses: actions/upload-artifact@v2
        with:
          name: examples-linux
          path: examples

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable

      - name: Run tests and build examples
        run: script/build.sh

      - name: Upload examples
        uses: actions/upload-artifact@v2
        with:
          name: examples-macos
          path: examples

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable

      # - name: Restore nuget packages
      #   run: nuget restore script\packages.config -PackagesDirectory script\nuget

      - name: Run tests and build examples
        run: script/build.bat

      - name: Upload examples
        uses: actions/upload-artifact@v2
        with:
          name: examples-windows
          path: examples
